# Basic Information 
title: Hem Chandra Joshi
position: Research Scholar
affiliation: Indian Institute of Technology Roorkee
affiliation_link: https://www.iitr.ac.in/
affiliation_logo: ./assets/img/IIT_Roorkee.svg
email: hc_joshi(at)cs.iitr.ac.in

# Search Engine Optimization (SEO)
keywords: hem chandra joshi
canonical: 
description: Hem Chanda Joshi is a research scholar at Indian Institute of Technology Roorkee, India. His research lies in Fairness, Accountability, Transparent and Explainability in AI.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=CUASp0gAAAAJ&hl=en&oi=ao
# github_link: https://github.com/yaoyao-liu/
# linkedin: https://www.linkedin.com/in/liuyaoyao/
# twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: ./assets/img/hem.jpeg

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: HV0rAUdAxpfEQLOsVs0FcJTR2rKVI5sEQUZIDM-N_HY

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
